name: Lab2 CI CD

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Lab2 Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./GH_Actions/lab2

      - name: Run tests
        run: python -m unittest -v
        working-directory: ./GH_Actions/lab2

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: test   # ‚≠ê BONUS

    steps:
      - name: Deploy
        run: echo "deploying application"
